name: HQS build docs for all packages

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install qoqo_qiskit/[docs]
    - uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: latest
    - name: build
      run: |
        # qoqo_qiskit
        cd qoqo_qiskit/docs
        python -m sphinx -T -E -b html . _build/html
        cd ../../
        cp -r ./qoqo_qiskit/docs/_build/html ./documentation/src/qoqo_qiskit_api
        # Generating doc
        cd documentation/
        mdbook build

    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: documentation/book